/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;
import core.Library;
public class Main {

    public static void main(String[] args) {

        Library lib = new Library();

        boolean isImported = lib.someLibraryMethod();

        if (isImported){
            System.out.println("Library succesfully imported");
        }

    }
}
