/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bootcamp.java.spring.may;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
