/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package functionalChallenge;

import java.util.function.BinaryOperator;

public class App {

    public static Integer execute(BinaryOperator<Integer> op, int a , int b){
        return op.apply(a,b);
    }

}
